SUMMARY = "Allied Vision Video4Linux2 Viewer"
LICENSE = "GPL-2.0-or-later"
LIC_FILES_CHKSUM = "file://LICENSE.md;md5=435d4178fd08b25f9cf911f1c3a0ce1d"


AVT_GIT_REPO = "V4L2Viewer"
AVT_GIT_BRANCH = "main"
SRCREV = "d765360fe0a30fb1d90c2dbe217ccbbe5f6aa34e"

inherit avt-git

DEPENDS:append = " qtbase "

S = "${WORKDIR}/git"

PV = "2.3.0+git${SRCPV}"

do_install() {
	install -d ${D}${bindir}
	install -m 755 ${B}/V4L2Viewer ${D}${bindir}/V4L2Viewer
    chrpath -d ${D}${bindir}/V4L2Viewer
}
